#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ "$1" = "--skip-webp" ]; then
  echo "Skipping WebP optimization..."
else
  if [ -x "$basedir/node" ]; then
    "$basedir/node"  "$basedir/optimization/webp.js"
    ret=$?
  else 
    node  "$basedir/optimization/webp.js"
    ret=$?
  fi
fi

exit $ret
