#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

cd "$basedir/../../Front" || exit

if [ "$1" = "--skip-svelte" ]; then
  echo "Skipping Svelte build..."
else
  npm run build
  ret=$?
  if [ $ret -ne 0 ]; then
    echo "npm run build failed. Exiting."
    exit $ret
  fi
fi

cd "../Server/lib" || exit

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/node_modules/grunt/bin/grunt" "$@"
  ret=$?
else 
  node  "$basedir/node_modules/grunt/bin/grunt" "$@"
  ret=$?
fi
exit $ret
